server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/elasticsearch?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.youngzy.es: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.youngzy.es.hotel.pojo